// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhnjhihwoxznauccaiew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobmpoaWh3b3h6bmF1Y2NhaWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDUzNzcsImV4cCI6MjA1OTA4MTM3N30.6k02_YnqL0cbuipWCChFLn-gPQuHwW2O83QeFEiZFbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);